#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     topLeft,       tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     topRight,      tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
#include "../etc/Clamp.fn"
#include "../etc/Scales.var"
#include "../etc/ScaleJoystick.fn"
#include "../movement/TwoMotors.fn"
#include "../controller/GetJoystick.fn"
#include "../controller/InitController.fn"
#include "../teleop/JoystickMove.fn"

task main()
{
	while(true)
	{
		initController();
		if(getJoystick(1, 1, 'y') < 5 && getJoystick(1, 1, 'y') > -5 && getJoystick(1, 1, 'x') < 5 && getJoystick(1, 1, 'x') > -5)
			joystickMove(2, 2, 50, CUBE_SCALE);
		else joystickMove(1, 10, 100, LINNEAR_SCALE);
	}
}
