#pragma config(Hubs,  S1, HTMotor,  HTServo,  HTMotor,  HTMotor)
#pragma config(Hubs,  S2, HTMotor,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Motor,  motorA,          captureLeft,   tmotorNXT, openLoop, reversed)
#pragma config(Motor,  motorB,          captureRight,  tmotorNXT, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     topRight,      tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     bottomRight,   tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     topLeft,       tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_2,     bottomLeft,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     mainLift,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     riseLift,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_1,     flagLift,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_2,     motorK,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C2_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_2,    grabber,              tServoStandard)
#pragma config(Servo,  srvo_S1_C2_3,    catch1,               tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C2_4,    catch2,               tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define MOVE_ONE_MAG 20
#define MOVE_ONE_DIR forward
#define MOVE_TWO_MAG 30
#define MOVE_TWO_DIR right
#define MOVE_THREE_MAG 30
#define MOVE_THREE_DIR forward
#define MOVE_FOUR_MAG 40
#define MOVE_FOUR_DIR foreward


task main()
{



}
