#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Hubs,  S2, HTServo,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     topLeft,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     bottomLeft,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     topRight,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     bottomRight,   tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     brush,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     grapple,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     mainlift,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     extra,         tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S2_C1_1,    sublift,              tServoContinuousRotation)
#pragma config(Servo,  srvo_S2_C1_2,    cadtch,                tServoStandard)
#pragma config(Servo,  srvo_S2_C1_3,    topple,               tServoStandard)
#pragma config(Servo,  srvo_S2_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
/*#include "../etc/Clamp.fn"
#include "../etc/Scales.var"
#include "../etc/ScaleJoystick.fn"
#include "../movement/SetSides.fn"
#include "../controller/GetJoystick.fn"
#include "../controller/InitController.fn"
#include "../teleop/JoystickMove.fn"
#include "../mod/modGrabber.fn"
#include "../mod/setFlag.fn"
#include "../mod/setLiftVector.fn"
#include "../mod/setCapture.fn"
#include "../mod/SetRise.fn"
#include "../threads/Drive.h"
#include "../threads/Lift.h"
#include "../mecanum/MoveDeg.fn"*/

task main()
{
	//StartTask(drive);
	//StartTask(lift);
	while(true) {
		getJoystickSettings(joystick);
	int num = joy1Btn(1);
	};
}
