#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     flag1,         tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     flag2,         tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "../motors/SetMotor.fn"

task main()
{
	nNxtButtonTask = -2;
	nNxtExitClicks = 3;


	while(true)
	{
		tButtons nBtn;
		if(nBtn == nNxtButtonPressed)
		{
			switch(nBtn)
			{
				case kRightButton:
					setMotor(flag1, 100);
					break;
				case kLeftButton:
					setMotor(flag1, 0);
					break;
			}
		}
	}



}
