#pragma config(Hubs,  S1, HTMotor,  HTServo,  HTMotor,  HTMotor)
#pragma config(Hubs,  S2, HTMotor,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Motor,  motorA,          captureLeft,   tmotorNXT, openLoop, reversed)
#pragma config(Motor,  motorB,          captureRight,  tmotorNXT, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     topRight,      tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     bottomRight,   tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     topLeft,       tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_2,     bottomLeft,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     mainLift,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     riseLift,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_1,     flagLift,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_2,     a,             tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C2_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_2,    grabber,              tServoStandard)
#pragma config(Servo,  srvo_S1_C2_3,    catch1,               tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C2_4,    catch2,               tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
#include "../etc/Clamp.fn"
#include "../etc/Scales.var"
#include "../etc/ScaleJoystick.fn"
#include "../movement/SetSides.fn"
#include "../controller/GetJoystick.fn"
#include "../controller/InitController.fn"
#include "../teleop/JoystickMove.fn"
#include "../mod/modGrabber.fn"
#include "../mod/setFlag.fn"
#include "../mod/setLiftVector.fn"
#include "../mod/setCapture.fn"
#include "../mod/SetRise.fn"
#include "../threads/Drive.h"
#include "../threads/Lift.h"
#include "../mecanum/MoveDeg.fn"

task main()
{

	StartTask(drive);
	StartTask(lift);

while(true) {}

/*	motor[topRight] = 60;
	wait1Msec(1000);
	motor[topRight] = 0;
	motor[topLeft] = 60;
	wait1Msec(1000);
	motor[topLeft] = 0;
	motor[bottomLeft] = 60;
	wait1Msec(1000);
	motor[bottomLeft] = 0;
	motor[bottomRight] = 60;
	wait1Msec(1000);
	motor[bottomRight] = 0;*/

	/*servo[catch1] = -256;
	servo[catch2] = 256;
	wait1Msec(2000);
	servo[catch1] = 0;
	servo[catch2] = 0;*/

}
