#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     spoolLeft,     tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     spoolRight,    tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
 * Spooler_10-21.c ~
 * Alex Jones for team 5105 Buffalo Wings
 *
 * Description: 	a simple unit test for the spooler that Raj has created
 *
 * Uses: 			to test the gear config on the test equipment.
 *
 * Dependancies:	NONE
 *
 * ~licensed under the MIT license included in this repositiory
*/
#include "JoystickDriver.c"
#include "../motors/SetMotor.fn"
#include "../controller/GetJoystick.fn"

task main()
{
	while(true)
	{
		getJoystickSettings(joystick);
		setMotor(spoolLeft, getJoystick(1, 1, 'y')/1.28);
		setMotor(spoolRight, getJoystick(1, 1, 'y')/1.28);
	}
}
