#pragma config(Hubs,  S1, HTMotor,  HTServo,  HTMotor,  HTMotor)
#pragma config(Hubs,  S2, HTMotor,  none,     none,     none)
#pragma config(Sensor, S3,     touch,          sensorTouch)
#pragma config(Sensor, S4,     HTSMUX,         sensorI2CCustom)
#pragma config(Motor,  motorA,          captureRight,  tmotorNXT, openLoop)
#pragma config(Motor,  motorB,          captureLeft,   tmotorNXT, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     topLeft,       tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     bottomLeft,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     topRight,      tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_2,     bottomRight,   tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     mainLift,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     riseLift,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_1,     flagLift,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_2,     motorK,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C2_1,    grabber,              tServoStandard)
#pragma config(Servo,  srvo_S1_C2_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//configure the sensor multiplexer
#include "..\drivers\mux\drivers\hitechnic-sensormux.h"

// Assuming the Sensor MUX is connected to NXT sensor port 4 (S4)
// Assuming the following sensors are connected to the Sensor MUX ports:
// Port 1: compass
// Port 2: gyro
// Port 3: ir
// Port 4: light
#include "..\drivers\mux\drivers\hitechnic-gyro.h"
#include "..\drivers\mux\drivers\hitechnic-compass.h"
#include "..\drivers\mux\drivers\lego-light.h"
#include "..\drivers\mux\drivers\hitechnic-irseeker-v2.h"
#define compass              msensor_S4_1
#define gyro		             msensor_S4_2
#define ir				           msensor_S4_3
#define light                msensor_S4_4
TSensorModes
/*
 * Spooler_10-21.c ~
 * Alex Jones for team 5105 Buffalo Wings
 *
 * Description: 	a simple unit test for the spooler that Raj has created
 *
 * Uses: 			to test the gear config on the test equipment.
 *
 * Dependancies:	NONE
 *
 * ~licensed under the MIT license included in this repositiory
*/
#include "JoystickDriver.c"
#include "../motors/SetMotor.fn"
#include "../controller/GetJoystick.fn"

task main()
{
	while(true)
	{
		getJoystickSettings(joystick);
		setMotor(spoolLeft, getJoystick(1, 1, 'y')/1.28);
		setMotor(spoolRight, getJoystick(1, 1, 'y')/1.28);
	}
}
