#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop)
#pragma config(Servo,

//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
#include "../etc/Clamp.fn"
#include "../movement/TwoMotors.fn"
#include "../controller/GetJoystick.fn"
#include "../controller/InitController.fn"
#include "../teleop/JoystickMove.fn"

task main()
{
while(true)
 {
   initController();
   joystickMove(1, 10, 100, 1);
 }

}
